server:
  port: 19100
spring:
  application:
    name: spring-boot-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/tsw_demo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: ${db.username}
    password: ${db.password}
  boot:
    demo:
      account:
        url: ${account.url}
      inventory:
        url: ${inventory.url}
