server:
  port: 19111
spring:
  application:
    name: spring-cloud-zipkin-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/tsw_demo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: ${db.username}
    password: ${db.password}
  zipkin:
    baseUrl: ${zipkin.url}
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    ROOT: info